"""
AIRS Internationalization (i18n) Module
Provides multi-language support (English, Polish, German) for assessment reports,
domain titles, remediation procedures, policy templates, and transactional emails.
"""

from typing import Dict, Any

TRANSLATIONS = {
    "en": {
        "report_title": "AI RISK SHIELD ASSESSMENT REPORT",
        "report_subtitle": "Responsible AI Governance & Visual Audit",
        "governance_index": "AIRS GOVERNANCE INDEX",
        "maturity_level": "Maturity Level",
        "company_profile": "Company Profile",
        "executive_summary_title": "Executive Summary",
        "high_risk_alert_title": "⚠️ EU AI Act Regulatory High-Risk Alert",
        "section_1_title": "📊 Section 1 — Visual Governance & Radar Evaluation",
        "radar_title": "AIRS 7-Domain Maturity Radar",
        "procedures_title": "📋 Detailed Remediation Procedures",
        "templates_title": "📑 Ready-to-Use Policy & Clause Templates",
        "disclaimer_title": "LEGAL DISCLAIMER",
        "domains": {
            "AI Governance": "AI Governance",
            "Data Protection & Privacy": "Data Protection & Privacy",
            "Human Oversight": "Human Oversight",
            "Transparency & Incidents": "Transparency & Incidents",
            "Intellectual Property": "Intellectual Property",
            "HR & High-Risk Systems": "HR & High-Risk Systems",
            "AI Literacy & Operations": "AI Literacy & Operations"
        },
        "email": {
            "subject": "[AIRS AUDIT REPORT] AI Risk & Liability Assessment — {company_name}",
            "header": "Responsible AI Governance Audit",
            "greeting": "Dear Executive,",
            "body": "Your Responsible AI Risk Assessment report for <strong>{company_name}</strong> has been generated by the AIRS engine.",
            "button": "Open Full Online Report"
        }
    },
    "pl": {
        "report_title": "RAPORT AUDYTU AI RISK SHIELD",
        "report_subtitle": "Zarządzanie AI i Audyt Ryzyka Regulacyjnego",
        "governance_index": "INDEKS DOJRZAŁOŚCI AIRS",
        "maturity_level": "Poziom Dojrzałości",
        "company_profile": "Profil Organizacji",
        "executive_summary_title": "Podsumowanie Zarządcze",
        "high_risk_alert_title": "⚠️ Ostrzeżenie Regulacyjne EU AI Act (Wysokie Ryzyko)",
        "section_1_title": "📊 Sekcja 1 — Wizualna Ocena Dojrzałości i Wykres Radaryzacyjny",
        "radar_title": "Wykres Dojrzałości 7 Domen AIRS",
        "procedures_title": "📋 Procedury Naprawcze i Plan Wdrożenia",
        "templates_title": "📑 Gotowe Szablony Polityk i Klauzul Umownych",
        "disclaimer_title": "ZASTRZEŻENIE PRAWNE",
        "domains": {
            "AI Governance": "Nadzór i Polityka AI",
            "Data Protection & Privacy": "Ochrona Danych i Prywatność",
            "Human Oversight": "Nadzór Ludzki (HITL)",
            "Transparency & Incidents": "Przejrzystość i Incydenty",
            "Intellectual Property": "Własność Intelektualna",
            "HR & High-Risk Systems": "Systemy Wysokiego Ryzyka (HR)",
            "AI Literacy & Operations": "Kompetencje i Operacje AI"
        },
        "email": {
            "subject": "[RAPORT AIRS] Audyt Ryzyka i Odpowiedzialności AI — {company_name}",
            "header": "Audyt Odpowiedzialnego Korzystania z AI",
            "greeting": "Dzień dobry,",
            "body": "Twój raport audytowy odpowiedzialnego korzystania z AI dla firmy <strong>{company_name}</strong> został wygenerowany przez silnik AIRS.",
            "button": "Otwórz Pełny Raport Online"
        }
    }
}

class I18n:
    @staticmethod
    def get(key: str, lang: str = "en") -> Any:
        lang_dict = TRANSLATIONS.get(lang.lower(), TRANSLATIONS["en"])
        return lang_dict.get(key, TRANSLATIONS["en"].get(key, key))

    @staticmethod
    def get_domain_name(domain_key: str, lang: str = "en") -> str:
        lang_dict = TRANSLATIONS.get(lang.lower(), TRANSLATIONS["en"])
        return lang_dict.get("domains", {}).get(domain_key, domain_key)
