"""
AIRS Report Generator Module (Bilingual Multilingual Version)
Aggregates assessment scoring objects into structured report data dicts,
utilizing LLMSynthesizer for executive summary generation in both English and Polish.
"""

from typing import Dict, Any, List
from .mapper import AIRSAssessmentObject
from .scoring import ScoringReport
from .chart_generator import SVGChartGenerator
from .llm_synthesizer import LLMSynthesizer

class AIReportGenerator:
    @staticmethod
    def generate_report_content(assessment: AIRSAssessmentObject, scoring: ScoringReport) -> Dict[str, Any]:
        company = assessment.company
        answers = assessment.answers
        adoption = assessment.ai_adoption

        # Generate English (default) and Polish Narratives
        exec_summary_en = LLMSynthesizer.generate_narrative(
            company_name=company.name,
            industry=company.industry,
            company_size=company.company_size,
            score=scoring.overall_score,
            risk_level=scoring.risk_level,
            maturity=scoring.maturity_level,
            tools=adoption.tools,
            high_risk_flags=[{"system_name": f.system_name} for f in scoring.high_risk_flags],
            data_upload=answers.confidential_data_upload,
            lang="en"
        )

        exec_summary_pl = LLMSynthesizer.generate_narrative(
            company_name=company.name,
            industry=company.industry,
            company_size=company.company_size,
            score=scoring.overall_score,
            risk_level=scoring.risk_level,
            maturity=scoring.maturity_level,
            tools=adoption.tools,
            high_risk_flags=[{"system_name": f.system_name} for f in scoring.high_risk_flags],
            data_upload=answers.confidential_data_upload,
            lang="pl"
        )

        # Generate Vector SVG Charts
        radar_svg = SVGChartGenerator.generate_radar_chart(scoring.domain_results, width=400, height=340)
        gauge_svg = SVGChartGenerator.generate_maturity_gauge(scoring.overall_score, width=500, height=50)

        # Phased Timelines
        phase_7 = [p for p in scoring.remediation_procedures if p.timeline == "Days 1–7"]
        phase_30 = [p for p in scoring.remediation_procedures if p.timeline == "Days 8–30"]
        phase_90 = [p for p in scoring.remediation_procedures if p.timeline == "Days 31–90"]

        # Templates
        templates = []
        for proc in scoring.remediation_procedures:
            if proc.starter_template:
                templates.append({
                    "title": proc.title,
                    "template": proc.starter_template
                })

        # EU AI Act Commentary
        hr_commentary_en = ""
        hr_commentary_pl = ""
        if scoring.high_risk_flags:
            flag_names = ", ".join([f.system_name for f in scoring.high_risk_flags])
            hr_commentary_en = (
                f"⚠️ **EU AI Act Regulatory High-Risk Notice:** Your organization reported using AI for automated evaluation ({flag_names}). "
                f"Under Annex III / Article 28 / Article 50 of the EU AI Act, these use cases trigger legal obligations including mandatory "
                f"risk management, technical documentation, logging, transparency notices, and human oversight."
            )
            hr_commentary_pl = (
                f"⚠️ **Ostrzeżenie Regulacyjne EU AI Act (Wysokie Ryzyko):** Twoja organizacja zgłosiła wykorzystanie AI do automatycznej oceny ({flag_names}). "
                f"Zgodnie z Załącznikiem III / Art. 28 / Art. 50 EU AI Act, te zastosowania nakładają obowiązki prawne obejmujące zarządzenie ryzykiem, "
                f"dokumentację techniczną, logowanie zdarzeń, klauzulę przejrzystości i nadzór ludzki."
            )

        disclaimer = "This document is an automated decision-support assessment generated by the AIRS engine. It does not constitute formal legal advice."

        return {
            "company_name": company.name,
            "company_email": company.email,
            "country": company.country,
            "industry": company.industry,
            "company_size": company.company_size,
            "tools": adoption.tools,
            "overall_score": scoring.overall_score,
            "risk_level": scoring.risk_level,
            "maturity_level": scoring.maturity_level,
            "exec_summary_en": exec_summary_en,
            "exec_summary_pl": exec_summary_pl,
            "executive_summary": exec_summary_en, # Default EN
            "high_risk_commentary_en": hr_commentary_en,
            "high_risk_commentary_pl": hr_commentary_pl,
            "high_risk_commentary": hr_commentary_en,
            "radar_svg": radar_svg,
            "gauge_svg": gauge_svg,
            "phase_7_days": phase_7,
            "phase_30_days": phase_30,
            "phase_90_days": phase_90,
            "policy_templates": templates,
            "disclaimer": disclaimer
        }
